import Head from 'next/head'
import Layout from '../components/landing/layout'
import Header from '../components/landing/header'
import Products from '../components/landing/products'
import Subscribe from '../components/landing/subscribe'

export default function Home() {
  return (
    <>
      <Head>
        <title>Leyli Shoper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header/>
        <Products/>
        <Subscribe/>
      </Layout>
    </>
  )
}
